# Generated by Django 3.1.7 on 2021-04-20 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_slug', models.CharField(max_length=200)),
                ('category_img', models.CharField(max_length=200)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_slug', models.CharField(max_length=200)),
                ('product_img', models.CharField(max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('product_amount', models.IntegerField(default=0)),
                ('product_sale', models.IntegerField(default=0)),
                ('product_detail', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webbanhang.category')),
            ],
        ),
    ]
