# Generated by Django 3.1.7 on 2021-04-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbanhang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_img',
            field=models.ImageField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(max_length=200),
        ),
    ]
