# Generated by Django 3.1.7 on 2021-04-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbanhang', '0002_auto_20210420_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to='img/category'),
        ),
    ]
