# Generated by Django 3.1.7 on 2021-05-20 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webbanhang', '0008_auto_20210520_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webbanhang.user'),
            preserve_default=False,
        ),
    ]
