# Generated by Django 3.1.7 on 2021-06-09 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webbanhang', '0010_auto_20210609_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_comment',
            new_name='product_cmt',
        ),
    ]
